### ISSUE TITLE
Create a Jameggy Jellobee Drink

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#31] opened 2019-03-26 13:30 UTC
It should, of course, contain an egg, and jam.

**Comment by gthole** [comment] 2019-03-26 19:31
Whoa.  Yes.

Though I'd say that a "jam-evocative" drink would be perfectly reasonable without resorting to the whole jam jar.  (But hey, who am I to stop you if [that's your jam](https://barkpost.com/wp-content/uploads/2015/03/pun-dog-pun-husky-00.jpg)?)

**Comment by jelloeggy** [comment] 2019-03-26 23:33
Well it doesn't have to be a jam-flavored drink, just include jam. 

There is the temptation to make it jello-flavored, but that way seems fraught with peril.

**Comment by jelloeggy** [comment] 2019-03-26 23:50
Jameggy Jellobee version 1:
Delicious rummy flip, though not at all jam flavored and too wintry for this assignment:
1 egg
1.25 oz rum
1 oz cynar
1 tbsp jam (blackberry)

garnish with bitters

**Comment by jelloeggy** [comment] 2019-03-27 00:08
V2 - closer.

1 egg
1.5 Genever
1 tbsp jam
.75 Maurin Quina

**Comment by gthole** [comment] 2019-03-27 09:48
Hmm - sounds tasty.  If you're up for more experimentation, what about a cognac and apricot jam fizz?

**Comment by jelloeggy** [comment] 2019-03-27 12:37
:jackbug_salute:

Wait do you actually mean a fizz, like with soda water, or a Greg-fizz with
egg white?

**Comment by gthole** [comment] 2019-03-27 17:11
Uhm.  Left as an exercise to the reader?  (In the cold light of day, I'm less convinced cognac/apricot would be tasty, but still curious.)

**Comment by jelloeggy** [comment] 2019-03-27 17:19
Oh, I think it will be quite tasty, but I guess now it's on me to make it
so.

**Comment by gthole** [comment] 2019-03-27 17:29
... well the issue is assigned to you. `:D`  I'm just curious to see what you do.

**Comment by jelloeggy** [comment] 2019-03-28 01:03
V3

1 tbsp (ish) apricot jam
.5 citrus (lime or lemon)
1.5 brandy
.5 strega
1 egg white

Quite delicious and a lovely yellow color. I'd like to add something to make it really pop or have a tiny bit more depth instead of just being a tasty sweet fruity drink. Thinking about salt, or something to swap in for the strega, or bitters, or...something.

**Comment by gthole** [comment] 2019-03-29 01:59
Tiny splash of sfumato?

**Comment by jelloeggy** [comment] 2019-04-05 23:45
Initial version deployed for QA.

**Comment by gthole** [comment] 2019-04-06 00:18
Very excited to try this.  Gonna need to pick up some apricot jam, though (and maybe some Sfumato.)

**Comment by jelloeggy** [comment] 2019-04-06 00:25
Oh, try any jam! I'd actually be curious what another one does. But yes, of
course, you must have sfumato on hand, so whatever makes that happen.

**Comment by gthole** [comment] 2019-04-07 18:55
OK, so I did this with my last spoonful of cherry jam and I was distracted by the Strega.  So I did it again with Cynar subbed for the Strega and strawberry jam and it was a lot smoother but the strawberry was a little too dominant.

You want to try a Cynar sub with Apricot?  (While I navigate the rest of the afternoon, two flips in ...)

**Comment by jelloeggy** [comment] 2019-04-07 19:54
Ah now you see my dilemma! It's a tricky one. I'm honestly wondering if I
should just ditch the citrus and the Brandy and lean into amaro and jam, go
for lucious instead of complex and light. The egg has a quality of
mellowing out whatever was there before so it's tricky to titrate in
advance.

And a two flip afternoon sounds like a good time, but not as good as a
three flip afternoon and a nap. Just saying.

**Comment by gthole** [comment] 2019-04-07 20:34
The danger of leaning into the amaro is that we just end up with a Cynar Flip again (which is certainly not the worst fate.)  That said, I like the idea of jam, brandy, amaro, egg.

Ooh, how about those plus blackberry jam and a tawny port?

**Comment by jelloeggy** [comment] 2019-04-07 20:38
:squinch:

So kind of like my first one, but with brandy for rum?

**Comment by gthole** [comment] 2019-04-07 21:06
uhm.  :shipit:  (Also, port.)

1.5oz Brandy
.5 oz Cynar
.5 oz Port
1 tbspn Blackberry Jam
1 egg

**Comment by jelloeggy** [comment] 2019-04-07 21:23
Did you try that one? I'm going to start simple and try:

Jam (plum, because that's what I got)
Amaro nonino
Brandy
Egg

Unless unless other (dr)in(k)spiration strikes...

**Comment by jelloeggy** [comment] 2019-04-07 21:35
So I don't know if it's right but:
1.5 Brandy
1.5 Nonino
1 tbsp jam (makers choice)
Garnish with tiki bitters (or whatever you got)

Yum yum yum

**Comment by jelloeggy** [comment] 2019-04-07 21:44
*right for this drink name

**Comment by gthole** [comment] 2019-04-07 22:54
Sadly the only jam I have left is strawberry, so further jellobee experimentation will have to wait until after a grocery run.  (How well does the Nonino play with the egg?)

**Comment by jelloeggy** [comment] 2019-04-07 23:13
At this point I've had a Deep 6 (well, a Deep 70) so I'm going to trust my
previous judgement of "yum" and say "it played well".

**Comment by gthole** [comment] 2019-04-08 00:04
Mmm Deep 70.  I highly recommend a My Word is Gold, FYI.  I'll plan to get some port and blackberry jam soon and keep this research train going.

**Comment by jelloeggy** [comment] 2019-04-08 00:19
Oh? I might have one more drink in me tonight. Research is very important,
and your scientific diligence is appreciated.

**Comment by gthole** [comment] 2019-08-10 15:13
🍸 :grewesome:

**Closed by gthole** 2019-08-10 15:13 UTC
Labels: enhancement
